### ISSUE TITLE
Évaluation ODEVA

### ISSUE THREAD

**Issue by Thms-Brnrd** [seblucas/odeva#7]
Les soutenances de projet PLATINE ayant eu lieu aujourd'hui pour les Formation Initiale, pouvez-vous nous indiquer comment se déroule l'évaluation d'ODEVA svp ?
Devons-nous vous fournir l'URL de nos projets PLATINE sur GitHub ?

Merci d'avance :)

**Comment by seblucas** [comment]
Jusqu'à preuve du contraire, je ne note pas. Ce sont les autres professeurs qui intègrent les parties liées à ODEVA dans leur notation.
